output: source-vektoriai.o funkcijos.o mediana.o vidurkis.o
	g++ source-vektoriai.o funkcijos.o mediana.o vidurkis.o -o output

main.o: main.cpp
	g++ -c source-vektoriai.cpp

funkcijos.o: funkcijos.cpp
	g++ -c funkcijos.cpp

mediana.o: mediana.cpp
	g++ -c mediana.cpp

vidurkis.o: vidurkis.cpp
	g++ -c vidurkis.cpp

clean:
	rm *.o output
